### ISSUE TITLE
ABOUT MININGCERTAIN:73

### ISSUE THREAD

**Issue by EgeN7** [fatpigsarefat/Quests#1]
I made 20 quests and they are very cool! Except for the Redstone Ore quest. Type is: MININGCERTAIN:73 which is redstone ore. But its working only in creative gamemode. When we choose survival and break some redstone ores, the counter isn't counting the blocks while breaking them on survival gamemode. What is the problem?

**Comment by fatpigsarefat** [comment]
Resolved over Discord (fixed in a later update)
