### ISSUE TITLE
config.yml replaced

### ISSUE THREAD

**Issue by DracarysPro** [fatpigsarefat/Quests#3]
Whenever a yaml error is present in the config.yml file, the config gets replaced with the default one, deleting all the current work. I think there are better ways to handle this, like saving a backup yml when an error occurs.

**Comment by fatpigsarefat** [comment]
Noted. I'll keep this in mind for the recode.

**Comment by fatpigsarefat** [comment]
This will be fixed in the upcoming recode.
https://github.com/fatpigsarefat/Quests-2
