### ISSUE TITLE
Cannot set item data for display item of quests.

### ISSUE THREAD

**Issue by srthd** [fatpigsarefat/Quests#6]
I found out that you cannot use block data when setting the display item of a quest.
It works for the categories and everything else but not the quests.
https://i.imgur.com/3KCkjsl.png
https://i.imgur.com/j6LbJ4b.png

**Comment by fatpigsarefat** [comment]
Update: https://www.spigotmc.org/resources/▶-quests-◀-set-up-goals-for-players.23696/update?update=222096
