### ISSUE TITLE
[Bad English] Bug Farm Quests

### ISSUE THREAD

**Issue by Yhenko** [fatpigsarefat/Quests#8]
Hi, bad english, first of all
Very nice plugin, i think its the best Quests plugins, keep it updated! ♥

Quests with breakblock like Crops (potatoes, wheat, seeds), i can plant the seed and just break it and its count to the quest, bad english again, hope u can understand me

**Comment by fatpigsarefat** [comment]
Have you tried adding data codes (such as :7 that means a fully grown crop).

**Comment by Yhenko** [comment]
Thx, i didnt know that xD ♥♥
