### ISSUE TITLE
2 Suggestions c:

### ISSUE THREAD

**Issue by Yhenko** [fatpigsarefat/Quests#9]
Hi, bad english, again xd.

• Add a cancel button
• Fix ASAP /quests a moddata (for testing quests)
• Add some method to prevent players for place and breaking, just for quests like "Farm 64 Sugar Cane" or "Break 64 Emerald Ore"

**Comment by srthd** [comment]
agreed

**Comment by fatpigsarefat** [comment]
/quests a moddata has been added in v2.0.6-beta
